// <auto-generated />
using AppTareas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppTareas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppTareas.Models.ListaCompartida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ListaTareasId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCompartidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListaTareasId");

                    b.HasIndex("UsuarioCompartidoId");

                    b.ToTable("ListasCompartidas");
                });

            modelBuilder.Entity("AppTareas.Models.ListaTareas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ListaTareas");
                });

            modelBuilder.Entity("AppTareas.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Completada")
                        .HasColumnType("bit");

                    b.Property<string>("Etiqueta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListaTareasId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListaTareasId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("AppTareas.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AppTareas.Models.ListaCompartida", b =>
                {
                    b.HasOne("AppTareas.Models.ListaTareas", "ListaTareas")
                        .WithMany("ListasCompartidas")
                        .HasForeignKey("ListaTareasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppTareas.Models.Usuario", "UsuarioCompartido")
                        .WithMany("ListasCompartidas")
                        .HasForeignKey("UsuarioCompartidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ListaTareas");

                    b.Navigation("UsuarioCompartido");
                });

            modelBuilder.Entity("AppTareas.Models.ListaTareas", b =>
                {
                    b.HasOne("AppTareas.Models.Usuario", "Usuario")
                        .WithMany("ListasTareas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppTareas.Models.Tarea", b =>
                {
                    b.HasOne("AppTareas.Models.ListaTareas", "ListaTareas")
                        .WithMany("Tareas")
                        .HasForeignKey("ListaTareasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ListaTareas");
                });

            modelBuilder.Entity("AppTareas.Models.ListaTareas", b =>
                {
                    b.Navigation("ListasCompartidas");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("AppTareas.Models.Usuario", b =>
                {
                    b.Navigation("ListasCompartidas");

                    b.Navigation("ListasTareas");
                });
#pragma warning restore 612, 618
        }
    }
}
